version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  app:
    build: 
      context: ./manAndVanBackend
      dockerfile: Dockerfile
    volumes:
      - ./manAndVanBackend:/manAndVanBackend
    ports:
      - 4000:4000
    environment:
      - DATABASEURI=mongodb://mongodb:27017/turbodatabase
    depends_on:
      - mongodb
  front:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ./:/front
    ports:
      - 3000:3000
    command: ["npm","start"]
